version: 0.0
os: linux

files:
 - source: files/index.html
   destination: /var/www/html

permissions:
 - object: /var/www/html
   pattern: index.html
   owner: apache
   group: 644
   type:
     - file
 - object: scripts
   pattern: webserver-stop.sh
   owner: apache
   mode: 755
   type:
     - file
 - object: scripts
   pattern: webserver-start.sh
   owner: apache
   mode: 755
   type:
     - file
     
hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.sh
    - location: scripts/delete-old-index.sh
  AfterInstall:
    - location: scripts/sleep.sh
    - location: scripts/webserver-start.sh
